language: java
jdk:
- oraclejdk8
sudo: required
cache:
  directories:
  - "$HOME/.m2"
notifications:
  on_success: never
  on_failure: always
services:
- docker
- redis
install: true
script: mvn clean install docker:build