# ===================================================================
# Spring Boot configuration.
# ===================================================================
spring:
    redis:
        database: 0
        host: localhost
        password: ''
        port: 6379
        timeout: 0
        pool:
            max-active: 8
            max-idle: 8
            max-wait: -1
            min-idle: 0

